server:
  port: 8188
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/jiaoyou_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: 38A0O1jEPOE
      max-active: 100
      max-wait: 30000
      min-idle: 10
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/audiobox?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: 38A0O1jEPOE
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 100
      max-wait: 30000
      min-idle: 10
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  jpa:
    database: mysql
    #控制台显示SQL
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: detect
  redis:
    host: localhost
    port: 6379
    timeout: 1000
logging:
  file:
    path: /home/jiaoyou/projects/audiobox/duai/logs
  level:
    root: info
    #okhttp3:
    # OkHttpClient: FINE

num: 1
colony:
  ser th: /home/jiaoyou/projects/audiobox/duai/logs
vers: heep://localhost:8189/
