server:
  port: 8003
  shutdown: graceful
  tomcat:
#    accesslog:
#      enabled: true
#      pattern: '%h %l %u %t "%r" %s %b bytes %D ms'
#      directory: /home/dc2-user/projects/audiobox/duai/tomcat
    threads:
      max: 1024

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/game_editor_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: 38A0O1jEPOE
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/audiobox?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#      jdbc-url: jdbc:mysql://localhost:3306/game_editor_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: 38A0O1jEPOE
      driver-class-name: com.mysql.cj.jdbc.Driver
    analysis:
      jdbc-url: jdbc:mysql://localhost:3306/analysis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#      jdbc-url: jdbc:mysql://localhost:3306/game_editor_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: 38A0O1jEPOE
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    #控制台显示SQL
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: detect
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  pid:
    file: /home/dc2-user/projects/audiobox/duai/app.pid

logging:
  level:
    root: info
    okhttp3:
      OkHttpClient: FINE
  file:
    path: /home/dc2-user/projects/audiobox/duai/logs

csvDic: /home/dc2-user/projects/audiobox/duai/csv/
csvChildDic: /home/dc2-user/projects/audiobox/duai/childCsv/
num: 1